# Generated by Django 5.2.17 on 2026-09-29 11:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('land_area', models.FloatField(help_text='Luas lahan dalam meter persegi (m2).', validators=[django.core.validators.MinValueValidator(0.01)])),
                ('planting_medium', models.CharField(choices=[('soil', 'Tanah'), ('hydroponic', 'Hidroponik')], max_length=20)),
                ('environment_snapshot', models.JSONField(default=dict)),
                ('recommended_plants', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'recommendation histories',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
