# Generated by Django 5.2.17 on 2026-09-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perenual_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('sayur', 'Sayur'), ('buah', 'Buah'), ('herbal', 'Herbal'), ('hias', 'Hias')], max_length=20)),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('humidity_min', models.FloatField(blank=True, null=True)),
                ('humidity_max', models.FloatField(blank=True, null=True)),
                ('rainfall_min', models.FloatField(blank=True, null=True)),
                ('rainfall_max', models.FloatField(blank=True, null=True)),
                ('supports_soil', models.BooleanField(default=True)),
                ('supports_hydroponic', models.BooleanField(default=False)),
                ('sunlight', models.CharField(choices=[('full_sun', 'Full sun'), ('partial_shade', 'Partial shade'), ('shade', 'Shade')], max_length=20)),
                ('space_needed', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
