# Generated by Django 5.2.17 on 2026-09-29 06:25

import json

from django.db import migrations, models


def wrap_existing_sunlight_values(apps, schema_editor):
    """Turn the old single choice into JSON text before changing column type."""
    Plant = apps.get_model('plants', 'Plant')
    for plant_id, sunlight in Plant.objects.values_list('id', 'sunlight').iterator():
        value = [sunlight] if sunlight else []
        Plant.objects.filter(id=plant_id).update(sunlight=json.dumps(value))


def restore_single_sunlight_values(apps, schema_editor):
    """Keep the first value when rolling back to the former CharField."""
    Plant = apps.get_model('plants', 'Plant')
    for plant_id, sunlight in Plant.objects.values_list('id', 'sunlight').iterator():
        try:
            values = json.loads(sunlight) if isinstance(sunlight, str) else sunlight
        except (TypeError, ValueError):
            values = []
        value = values[0] if isinstance(values, list) and values else ''
        Plant.objects.filter(id=plant_id).update(sunlight=value)


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='care_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='drought_tolerant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='indoor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='perenual_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(
            wrap_existing_sunlight_values,
            restore_single_sunlight_values,
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
